routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('inicio');
});

//Route::get('/', 'HomeController@inicio');
Route::get('/ciudad/{id}/escorts', 'CityController@obtenerCiudadEspecifico');
Route::get('/publicaciones', 'HomeController@avisosChicas');
Route::get('/ciudad/{id}/anuncios', 'HomeController@anuncios');
Route::get('/ciudad/{id}/videos', 'HomeController@videos');
Route::get('/ciudad/{id}/perfiles', 'HomeController@perfiles');

   
    Route::get('/modelo/{id}/ver/calificar', 'UserController@calificacion')->name('perfil_modelo');
Route::post('/calificar', 'UserController@puntuacion');
Route::post('/calificar/cliente', 'UserController@puntuacioncliente');
Route::get('/noticia/{id}', 'NoticiaController@noticia');
Route::get('/aviso/{id}', 'AvisoController@verAviso');
Route::get('/ciudad/{id}', 'HomeController@ciudades');
Route::get('/video/{id}', 'VideoController@verVideo');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/modelo/{id}/ver', 'UserController@verModelo')->name('perfil_modelo');

Auth::routes();

Route::get('/migrate', function() {
    Artisan::call('migrate', ['--seed' => true]);
    return 'DONE'; //Return anything
});

Route::middleware(['auth'])->group(function(){
    Route::get('/obtenerUsuario', 'UserController@obtenerUsuario');
    Route::post('/obtenerUsuario', 'UserController@obtenerUsuarioEspecifico');
    Route::post('/registrarUsuario', 'UserController@registrarUsuario');
    Route::post('/actualizarUsuario', 'UserController@actualizarUsuario');
    Route::post('/actualizarUsuarioAviso', 'UserController@actualizarUsuarioAviso');
    Route::get('/obtenerUsuarios', 'UserController@obtenerUsuarios');
 
    Route::get('/editarUsuario/{id}', 'UserController@editarUsuario');

    Route::post('/usuario/quitarPrincipal', 'UserController@quitarPrincipal');
    Route::post('/usuario/subirPrincipal', 'UserController@subirPrincipal');

    Route::post('/usuario/quitarSlider', 'UserController@quitarSlider');
    Route::post('/usuario/subirSlider', 'UserController@subirSlider');

    Route::post('/usuario/quitarAgencia', 'UserController@quitarAgencia');
    Route::post('/usuario/agregarAgencia', 'UserController@agregarAgencia');
    
    Route::post('/usuario/ocultarModelo', 'UserController@ocultarModelo');
    Route::post('/usuario/mostrarModelo', 'UserController@mostrarModelo');

    Route::post('/usuario/eliminar', 'UserController@eliminarModelo');

    Route::get('/obtenerPagina', 'PageController@obtenerPagina');
    Route::post('/actualizarPagina', 'PageController@actualizarPagina');

    //Ciudades
    Route::get('/ciudades', 'CityController@index');
    Route::post('/ciudad/registrar', 'CityController@guardarCiudad');
    Route::post('/ciudad/actualizar', 'CityController@actualizarCiudad');
    Route::post('/ciudad/eliminar', 'CityController@eliminarCiudad');
    Route::post('/ciudad/restaurar', 'CityController@restaurarCiudad');

    Route::get('/avisosUsuario', 'AvisoController@indexUsuario');
    Route::post('/aviso/registrar', 'AvisoController@guardarAviso');
    Route::post('/aviso/actualizar', 'AvisoController@actualizarAviso');
    Route::post('/aviso/eliminar', 'AvisoController@eliminarAviso');

    //Rutas de sucursales
    Route::get('/noticias', 'NoticiaController@index');
    Route::post('/noticia/registrar', 'NoticiaController@guardarNoticia');
    Route::post('/noticia/actualizar', 'NoticiaController@actualizarNoticia');
    Route::post('/noticia/eliminar', 'NoticiaController@eliminarNoticia');
    Route::post('/noticia/restaurar', 'NoticiaController@restaurarNoticia');

    //Videos
    Route::post('/video/usuario', 'VideoController@indexUser');
    Route::get('/videosUsuario', 'VideoController@indexUsuario');
    Route::post('/video/registrar', 'VideoController@guardarVideo');
    Route::post('/video/eliminar', 'VideoController@eliminarVideo');
    Route::post('/video/registrar/usuario', 'VideoController@guardarVideoUsuario');
    
    
    

    
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nombre', 'usuario', 'password','busto', 'cintura', 'caderas', 'descripcion', 'tipo', 'perfil_url', 'sexo'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getUrlsAttribute(){
        $fotos = array();

        if($this->foto_uno_url != null) array_push($fotos, $this->foto_uno_url);
        if($this->foto_dos_url != null) array_push($fotos, $this->foto_dos_url);
        if($this->foto_tres_url != null) array_push($fotos, $this->foto_tres_url);
        if($this->foto_cuatro_url != null) array_push($fotos, $this->foto_cuatro_url);
        if($this->foto_cinco_url != null) array_push($fotos, $this->foto_cinco_url);
        if($this->foto_seis_url != null) array_push($fotos, $this->foto_seis_url);
        if($this->foto_siete_url != null) array_push($fotos, $this->foto_siete_url);
        if($this->foto_ocho_url != null) array_push($fotos, $this->foto_ocho_url);
        if($this->foto_nueve_url != null) array_push($fotos, $this->foto_nueve_url);
        if($this->foto_diez_url != null) array_push($fotos, $this->foto_diez_url);
        if($this->foto_once_url != null) array_push($fotos, $this->foto_once_url);
        if($this->foto_doce_url != null) array_push($fotos, $this->foto_doce_url);
        
        return $fotos;
  	}
}

resources/views/admin.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="../assets/images/favicon.png">
    <title>@yield('titulo', 'Placer Conce - Usuario')</title>
    
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('intranet/css/css-admin.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="shortcut icon" href="{{ asset('favicon.ico') }}">
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-144758712-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-144758712-1');
</script>

</head>

<body class="fixed-layout skin-red-dark">

    <div id="main-wrapper">
        <header class="topbar">
            <nav class="navbar top-navbar navbar-expand-md navbar-dark">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{{ url('/') }}">
                        <b>
                            TE
                        </b>
                        <span>
                            - TUS ENCUENTROS
                        </span> 
                    </a>
                </div>
                <!-- ============================================================== -->
                <!-- End Logo -->
                <!-- ============================================================== -->
                <div class="navbar-collapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"> <a class="nav-link nav-toggler d-block d-sm-none waves-effect waves-dark" href="javascript:void(0)"><i class="ti-menu"></i></a> </li>
                        <li class="nav-item"> <a class="nav-link sidebartoggler d-none d-lg-block d-md-block waves-effect waves-dark" href="javascript:void(0)"><i class="icon-menu"></i></a> </li>
                    </ul>
                    
                    <ul class="navbar-nav my-lg-0">
                        <li class="nav-item right-side-toggle"> <a class="nav-link  waves-effect waves-light" href="javascript:void(0)"><i class="ti-user"></i> {{ Auth::user()->nombre }}</a></li>
                    </ul>
                </div>
            </nav>
        </header>

        <div id="app">
            <aside class="left-sidebar">
                <!-- Sidebar scroll-->
                <div class="scroll-sidebar">
                    <nav class="sidebar-nav">
                        <ul id="sidebarnav">
                            <li class="nav-small-cap">--- MENÚ</li>
                            <li @click="menu=0"> <a class="waves-effect waves-dark" href="#" aria-expanded="false"><i class="fa fa-users"></i><span class="hide-menu">USUARIOS</span></a></li>
                            <li @click="menu=1"> <a class="waves-effect waves-dark" href="#" aria-expanded="false"><i class="fa fa-file"></i><span class="hide-menu">PÁGINA</span></a></li>
                            <li @click="menu=2"> <a class="waves-effect waves-dark" href="#" aria-expanded="false"><i class="fa fa-list"></i><span class="hide-menu"> NOTICIAS</span></a></li>
                            <li> <a class="waves-effect waves-dark" href="{{ route('logout') }}" aria-expanded="false" onclick="event.preventDefault();document.getElementById('logout-form').submit();"><i class="fas fa-sign-out-alt"></i> <span class="hide-menu">CERRAR SESIÓN</span> </a><form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">@csrf</form></li>
                        </ul>
                    </nav>
                </div>
            </aside>

            @yield('content')
        </div>

        <footer class="footer">
            Placer Conce 2019 ©. Todos los derechos reservados.
        </footer>
    </div>

    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('intranet/js/js-admin.js') }}"></script>
</body>

</html>

resources/views/anuncios.blade.php
@extends('layouts.modelo')

@section('contenido')


    <header class="page_header ds bottom_mask_add"><meta http-equiv="Content-Type" content="text/html; charset=gb18030">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-xl-3 col-lg-4 col-md-5 col-11">
                      <a href="{{ url('/') }}" class="logo logo_image">
                        <img src="{{ asset("principal/images/logo.png") }}" alt="" style="max-height: 60px;">
                    </a>
                </div>
                <div class="col-xl-6 col-lg-8 col-md-7 col-1">
                    <div class="nav-wrap">

                        <!-- main nav start -->
                        <nav class="top-nav">
                            <ul class="nav sf-menu">
                                <li class="active"><a href="#">Inicio</a></li>
                                <li><a href="#">Nosotros</a></li>
                                <li><a href="#">Agencia</a></li>
                            </ul>
                        </nav>
                        <!-- eof main nav -->

                        <!--hidding includes on small devices. They are duplicated in topline-->

                    </div>
                </div>
               
            </div>
        </div>
        <!-- header toggler -->
        <span class="toggle_menu"><span></span></span>
    </header>
    
         <section id="publicateEscort" class="contacts-section top_mask_add ds overflow-visible background-contact s-pt-70 s-pb-60 s-pt-md-95 s-pb-md-80 s-pt-xl-170 s-pb-xl-140 c-gutter-30">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-xl-4 animate" data-animation="scaleAppear">
                    <h2 class="mt-0 mb-40 contact-title text-uppercase">PUBLICATE EN</h2>
                    <span class="color-main fs-24 font-main text-uppercase">TUSENCUENTROS.CL</span>
                    
                 <!--   <div class="media mb-20">
                        <h5 class="fs-20 mb-0 min-w-100">Email:</h5>
                        <div class="media-body ml-0 d-flex flex-column">
                            <!--<span>contacto@tusencuentros.cl</span>
                        </div>
                    </div>-->
                </div>
                <!--.col-* -->
                <div class="fw-divider-space hidden-above-lg mt-20"></div>
                <div class="col-lg-7 col-xl-8 animate" data-animation="scaleAppear">                                
                    <form class="contact-form c-mb-20 c-gutter-20" method="POST" action="{{ route('register') }}">
                        @csrf
                        <input type="hidden" id="tipo_usuario" name="tipo_usuario" value="2">
    
                        @if($errors->any())
                            <div class="row">
                                <div class="col-12">
                                    <div class="alert alert-danger text-left">
                                        <ul>
                                            @foreach($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        @endif

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <input type="text" name="usuario" class="form-control" placeholder="Usuario">
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <input type="password" name="clave" class="form-control" placeholder="Clave">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <select name="sexo" id="sexo" class="form-control" style="height: 60px;">
                                        <option value="1" selected>MUJER</option>
                                        <option value="2">HOMBRE</option>
                                    </select>
                                    <button type="submit" class="btn-submit"><i class="fa fa-paper-plane"></i></button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <!--.col-* -->
            </div>
        </div>
    </section>

    @if(count($anuncios) > 0)
    <section id="anuncios" class="ds s-pt-70 s-pb-20 s-pb-sm-50 s-py-lg-100 s-py-xl-150">
      <h5 class="big-title" style="font-size: 60px;line-height: initial;text-align:center;COLOR:#FFF">¿BUSCAS ALGO O DESEAS PUBLICAR?</h5>
      <h5 class="big-title" style="font-size: 50px;line-height: initial;text-align:center">AVISOS ER&OacuteTICOS</h5>
      
        <div class="container">
 
            @foreach ($anuncios as $item)
                <div class="row c-gutter-60">
                    <div class="offset-lg-1 col-lg-10">
                        <article class="post event side-item bordered">
                            <div class="row">
                                <div class="col-xl-3">
                                    <div class="item-media cover-image">
                                        <center>
                                            <img src="{{ asset('storage/'. $item->usuario->perfil_url) }}" alt="img" class="img-responsive" height="200px">
                                            <div class="media-links">
                                                <a class="abs-link" title="" href="{{ url('aviso/' . $item->id) }}"></a>
                                            </div>
                                        </center>
                                    </div>
                                </div>

                                <div class="col-xl-9">
                                    <div class="item-content">
                                        <div class="entry-content">
                                            <h3 class="entry-title">
                                                <a href="{{ url('aviso/' . $item->id) }}" class="name">{{ $item->titulo}}</a>
                                            </h3>
                                            <p> {{ substr($item->contenido, 0, 300) }} ...</p>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </article>
                    </div>

                    <div class="fw-divider-space hidden-below-lg mt-50"></div>
                </div>
            @endforeach

        </div>
    </section>
@endif
 
	<script src="https://kit.fontawesome.com/f755b555f3.js"></script>

@endsection

resources/views/aviso.blade.php
@extends('layouts.modelo')

@section('contenido')

    <section class="page_breadcrumbs changeable ls gradient gorizontal_padding section_padding_20 columns_padding_5 table_section">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-3 text-center text-sm-left darklinks">
                    <a href="#">
                        <em>{{ $aviso->usuario->telefono }}</em>
                    </a>
                </div>
                <div class="col-sm-6 text-center">
                    <ol class="center-block breadcrumb">
                        <li>
                            <a href="{{ url('/escorts') }}">
                                Inicio
                            </a>
                        </li>
                        <li class="active">
                            <span> Aviso de {{ $aviso->usuario->nombre}}</span>
                        </li>
                    </ol>
                </div>
                <div class="col-sm-3 text-center text-sm-right">
                    <ul class="inline-dropdown inline-block">
                        <li class="dropdown login-dropdown">
                            @guest
								<li class="dropdown login-dropdown">
									<a class="topline-button" id="login" data-target="#" href="./" data-toggle="dropdown" aria-haspopup="true" role="button" aria-expanded="false">
										<i class="rt-icon2-user"></i>
									</a>
									<div class="dropdown-menu ds" aria-labelledby="login">
                                        <form role="form" method="POST" action="{{ route('login') }}">
                                            @csrf
											<div class="form-group">
												<label for="email" class="sr-only">Email</label>
                                                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
											</div>
											<div class="form-group">
												<label for="password" class="sr-only">Contraseña</label>
                                                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
											</div>
											<button type="submit" class="theme_button color1 bottommargin_0">
												Ingresar
											</button>
											<div class="checkbox-inline">
												<input type="checkbox" name="remember" id="remember" {{ old('remember') ? 'checked' : '' }}>
                                                <label for="remember" class="bottommargin_0"> Recuérdame</label>
											</div>
										</form>
									</div>
                                </li>                                  
                            @else
                                <a class="topline-button" id="login" href="{{ url('/home')}}" role="button" >
                                    <i class="rt-icon2-user"></i> {{ Auth::user()->nombre }}
                                </a>
                            @endguest
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <section class="ds model-page section_padding_70 section_padding_bottom_60 columns_padding_25">
        <div class="container">
            <div class="row">
                <div class="col-md-5 col-md-push-7">
                    <div class="vertical-item with_background models_square">
                        <div class="item-media">
                            <img src="{{ asset('storage/' . $aviso->usuario->perfil_url) }}" alt="Modelo">
                        </div>
                    </div>

                </div>

                <div class="col-md-7 col-md-pull-5">
                    <h2 class="muellerhoff topmargin_5 bottommargin_50 highlight">{{ $aviso->titulo }}</h2>
                    <h3></h3>
                    <p>
                        {!! $aviso->contenido !!}
                    </p>
                </div>

            </div>

            @if(count($aviso->usuario->urls) > 0)
                <div class="row">
                    <div class="col-md-12">
                        <div id="gallery-owl-carousel" class="owl-carousel" data-dots="true" data-items="3" data-responsive-lg="3" data-responsive-md="2" data-responsive-sm="2" data-responsive-xs="1">
                            @foreach ($aviso->usuario->urls as $item)
                                <div class="vertical-item gallery-extended-item with_background text-center">
                                    <div class="item-media text-center">
                                        <img src="{{ asset('storage/' . $item) }}" class="img-fluid" alt="Modelo" height="350px">
                                    </div>
                                </div>               
                            @endforeach
                        </div>
                    </div>
                </div>
            @endif
        </div>
    </section>

@endsection

resources/views/avisos.blade.php

    <section id="publicateAvisos" class="ds section_padding_70 parallax" style="background-image: url('../../principal/images/parallax/map2.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-sm-offset-3 col-sm-6 col-md-offset-3 col-md-6 col-lg-offset-3 col-lg-6 text-center">
                    <h2 class="big margin_0">Publica ahora ya</h2>
                    <h2 class="muellerhoff topmargin_5 bottommargin_50 highlight">Sin esperas</h2>

                    <form method="POST" action="{{ route('register') }}">
                        @csrf
                        <input type="hidden" id="tipo_usuario" name="tipo_usuario" value="2">

                        @if($errors->any())
                            <div class="row">
                                <div class="col-12">
                                    <div class="alert alert-danger text-left">
                                        <ul>
                                            @foreach($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        @endif
                        
                        <div class="form-group">
                            <label for="usuario" class="sr-only">Usuario
                                <span class="required">*</span>
                            </label>
                            <input type="text" aria-required="true" size="30" value="" name="usuario" id="usuario" class="form-control text-center" placeholder="Usuario" required value="{{ old('email') }}">
                        </div>
                        <div class="form-group">
                            <label for="name" class="sr-only">Contraseña
                                <span class="required">*</span>
                            </label>
                            <input type="password" aria-required="true" size="30" value="" name="clave" id="clave" class="form-control text-center" placeholder="Contraseña" required>
                        </div>
                        <div class="form-group">
                            <label for="email" class="sr-only">Confirmar contraseña
                                <span class="required">*</span>
                            </label>
                            <select name="sexo" id="sexo" class="form-control">
                                <option value="1">Mujer</option>
                                <option value="2">Hombre</option>
                            </select>
                        </div>
                        <br>
                        <button type="submit" id="contact_form_submit" name="contact_submit" class="theme_button color1 bottommargin_0">Registrarme</button>
                        <button type="reset" id="contact_form_clear" name="contact_clear" class="theme_button inverse bottommargin_0">Limpiar</button>
                    </form>
                </div>
            </div>
        </div>
    </section>

    <section id="avisos" class="ds section_padding_70 section_padding_bottom_50">
        <div class="container">
            <div class="row bottommargin_20">
                <div class="col-sm-12 text-center">
                    <h2 class="big margin_0">¿Buscas algo o deseas publicar?</h2>
                    <h2 class="muellerhoff topmargin_5 bottommargin_50 highlight">Avisos eróticos</h2>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <div class="panel-group">
                        @foreach($avisos as $item)
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <a href="{{ url('/aviso/' . $item->id) }}">
                                            <div class="row">
                                                <div class="col-md-3 col-sm-3 text-center">
                                                    <img src="{{ asset('storage/' . $item->usuario->perfil_url) }}" alt="..." class="img-fluid" width="120px">
                                                </div>
                                                <div class="col-md-9 col-sm-3 text-left">
                                                    <h3>{{ $item->titulo }}</h3>
                                                    <p>{{ substr($item->contenido, 0, 200) }} ... Ver más aquí</p>
                                                </div>
                                            </div>
                                        </a>
                                    </h4>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>

        </div>
    </section>

resources/views/calificar.blade.php
@extends('layouts.modelo')

@section('contenido')



 
    
     <!----------------------SISTEMA DE VALORACION------------------------------>
    <section class="ds s-pt-70 s-pb-50 s-pb-sm-70 s-py-lg-100 s-py-xl-150 c-gutter-40">
        <div class="container">
          
            <h2 style="text-align:center">&iquestTe atendiste con ella?</h2>
            <form action="/calificar" method="POST" role="form">
                 {{ csrf_field() }}
            <div class="row">
               <input type="number" name="id_usuario">
               <input type="text" name="atencion">
                 <input type="text" name="higiene">
                  <input type="text" name="fotos">
                   <input type="text" name="nota_final">
                 <button type="submit" class="btn-submit"><i class="fa fa-paper-plane"></i></button>
            </div>
            </form>
        </div>
        <div class="fw-divider-space hidden-below-lg mt-50"></div>
    </section>
    	<script src="https://kit.fontawesome.com/f755b555f3.js"></script>

@endsection